/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 6ac3233cb3148a9a471d361ca25bfccf)
// Runtime types generated with workerd@1.20250823.0 2025-08-27 
declare namespace Cloudflare {
	interface Env {
		AGENTS: KVNamespace;
		AI_AGENTS: KVNamespace;
		AI_MODELS: KVNamespace;
		SESSION: KVNamespace;
		IMAGES: KVNamespace;
		DEFAULT_TEXT_MODEL: "@cf/meta/llama-3.1-8b-instruct";
		FAST_TEXT_MODEL: "@cf/qwen/qwen1.5-0.5b-chat";
		ADVANCED_TEXT_MODEL: "@cf/meta/llama-3.3-70b-instruct-fp8-fast";
		CODE_MODEL: "@cf/qwen/qwen2.5-coder-32b-instruct";
		MATH_MODEL: "@cf/deepseek-ai/deepseek-math-7b-instruct";
		VISION_MODEL: "@cf/meta/llama-3.2-11b-vision-instruct";
		IMAGE_MODEL: "@cf/black-forest-labs/flux-1-schnell";
		SPEECH_MODEL: "@cf/openai/whisper-large-v3-turbo";
		TTS_MODEL: "@cf/deepgram/aura-1";
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}