name = "luc-de-zen-on-dev"
main = "src/worker-entry.js"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "SESSION"
id = "dev-session-store"
preview_id = "dev-session-store"

[vars]
PUBLIC_DEFAULT_MODEL = "@cf/google/gemma-3-12b-it"
PUBLIC_SITE_URL = "http://localhost:3006"
NODE_ENV = "development"

[dev]
ip = "127.0.0.1"
port = 8787
local_protocol = "http"
upstream_protocol = "https"

# Enable platform proxy for Astro dev server
[platform_proxy]
enabled = true