name = "huggingface-worker-production"
main = "./src/workers/huggingface-worker.ts"
compatibility_date = "2024-09-23"
node_compat = true

[vars]
# Set these in your Cloudflare dashboard or via wrangler secret
# AI_GATEWAY_ACCOUNT_ID = "your-account-id"
# AI_GATEWAY_ID = "your-gateway-id"

# Secrets (set via: wrangler secret put HUGGINGFACE_API_KEY)
# HUGGINGFACE_API_KEY = "your-huggingface-api-key"

# Optional: Add KV namespace for caching
# [[kv_namespaces]]
# binding = "AI_CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Optional: Add analytics
# [analytics_engine_datasets]
# binding = "AE"
# dataset = "huggingface_requests"
