name = "bielik-worker"
main = "src/workers/bielik-worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "bielik-worker"
route = { pattern = "bielik-worker.bonzokoles.workers.dev/*", zone_id = "" }

[env.development]
name = "bielik-worker-dev"

# Variables for BIELIK model configuration
[vars]
MODEL_NAME = "BIELIK-7B-Instruct"
MODEL_VERSION = "1.0.0"
MAX_TOKENS_DEFAULT = "512"
TEMPERATURE_DEFAULT = "0.7"
LANGUAGE = "pl"

# KV binding for storing conversation history
[[kv_namespaces]]
binding = "BIELIK_STORAGE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# Durable Objects for session management
[[migrations]]
tag = "v1"
new_classes = ["BielikSession"]

# Analytics for usage tracking
[analytics_engine_datasets]
[[analytics_engine_datasets.bindings]]
name = "BIELIK_ANALYTICS"
dataset = "bielik_usage"
