name = "deepseek-search-worker"
main = "src/workers/deepseek-worker.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "deepseek-search-worker"

[env.development]
name = "deepseek-search-worker-dev"

[ai]
binding = "AI"

# Variables for worker configuration
[vars]
WORKER_NAME = "deepseek-search-worker"
MODEL_NAME = "llama-3.1-8b-instruct"
LANGUAGE = "pl"
