name = "multi-ai-agent-worker"
main = "src/workers/multi-ai-agent-worker.ts"
compatibility_date = "2024-01-15"
worker_dev = false
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "multi-ai-agent-worker-production"

# Durable Objects configuration
[[durable_objects.bindings]]
name = "MULTI_AI_AGENT"
class_name = "MultiAIAgent"

# State migration for Durable Objects
[[migrations]]
tag = "v1"
new_classes = ["MultiAIAgent"]

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "AI_AGENTS"
id = "your-ai-agents-kv-namespace-id"
preview_id = "your-ai-agents-preview-kv-namespace-id"

[[kv_namespaces]]
binding = "SESSION"
id = "your-session-kv-namespace-id" 
preview_id = "your-session-preview-kv-namespace-id"

# Environment variables (set these in Cloudflare dashboard)
[vars]
# Will be set via wrangler secret put command or dashboard
# OPENAI_API_KEY
# ANTHROPIC_API_KEY  
# DEEPSEEK_API_KEY
# PERPLEXITY_API_KEY
# GOOGLE_AI_STUDIO_API_KEY
# HUGGINGFACE_API_KEY
# ELEVENLABS_API_KEY
# AI_GATEWAY_ACCOUNT_ID
# AI_GATEWAY_ID

# Optional Analytics Engine
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"

# Routes (uncomment and modify as needed)
# [[env.production.routes]]
# pattern = "agent.yourdomain.com/*"
# zone_name = "yourdomain.com"
