name = "polaczek-chat-assistant"
main = "./src/workers/polaczek-websocket.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
ENVIRONMENT = "production"
AI_MODEL_PROVIDER = "cloudflare"  # Options: cloudflare, openai, huggingface, anthropic
DEFAULT_LANGUAGE = "pl"

# KV namespace for knowledge base storage
[[kv_namespaces]]
binding = "KNOWLEDGE_BASE"
id = "23e11c0a4015498d9e199c529cbf3133"

# Durable Objects for session management (optional)
# [[durable_objects.bindings]]
# name = "CHAT_SESSIONS"
# class_name = "ChatSessions"

# R2 bucket for file storage (optional)
# [[r2_buckets]]
# binding = "FILES_STORAGE"
# bucket_name = "polaczek-files"
