name = "voice-ai-worker"
main = "src/workers/voice-ai-worker.ts"
compatibility_date = "2024-12-21"

[env.production]
ai = { binding = "AI" }
kv_namespaces = [
  { binding = "VOICE_AI_KV", id = "9288a144c0ad416893e1d260a084990a" }
]

[env.development]
ai = { binding = "AI" }
kv_namespaces = [
  { binding = "VOICE_AI_KV", id = "voice_ai_sessions_dev" }
]

# Enable Workers AI
[ai]
binding = "AI"

# KV for session storage
[[kv_namespaces]]
binding = "VOICE_AI_KV"
id = "9288a144c0ad416893e1d260a084990a"
preview_id = "voice_ai_sessions_dev"

# CORS settings for frontend
[env.production.vars]
ALLOWED_ORIGINS = "https://mybonzo.pl,https://www.mybonzo.pl"

[env.development.vars]
ALLOWED_ORIGINS = "http://localhost:4321,http://127.0.0.1:4321"
