name = "multi-ai-worker"
main = "src/workers/multi-ai-worker.ts"
compatibility_date = "2024-01-15"
worker_dev = false
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "multi-ai-worker-production"

# Environment variables (set these in Cloudflare dashboard)
[vars]
# Will be set via wrangler secret put command or dashboard
# OPENAI_API_KEY
# ANTHROPIC_API_KEY  
# DEEPSEEK_API_KEY
# PERPLEXITY_API_KEY
# GOOGLE_AI_STUDIO_API_KEY
# HUGGINGFACE_API_KEY
# ELEVENLABS_API_KEY
# AI_GATEWAY_ACCOUNT_ID
# AI_GATEWAY_ID

# Optional KV namespace for caching
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-kv-preview-namespace-id"

# Optional Analytics Engine
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"

# Routes (uncomment and modify as needed)
# [[env.production.routes]]
# pattern = "multi-ai.yourdomain.com/*"
# zone_name = "yourdomain.com"
