name = "bielik-worker"
main = "src/workers/bielik-worker.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "bielik-worker"

[env.development]
name = "bielik-worker-dev"

[ai]
binding = "AI"

# Variables for BIELIK model configuration
[vars]
WORKER_NAME = "bielik-worker"
MODEL_NAME = "llama-3.1-8b-instruct"
LANGUAGE = "pl"
BIELIK_MODE = "true"
