name = "mybonzo-main-chat"
main = "src/workers/main-chat-worker.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "mybonzo-main-chat"

[env.development]
name = "mybonzo-main-chat-dev"

[ai]
binding = "AI"

# Variables for main chat worker
[vars]
WORKER_NAME = "mybonzo-main-chat"
MODEL_NAME = "llama-3.1-8b-instruct"
LANGUAGE = "pl"
CHAT_TYPE = "main"
