name = "voice-avatar-worker"
main = "./src/workers/voice-avatar-worker.ts"
compatibility_date = "2024-03-08"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "voice-avatar-worker-production"

[env.staging]
name = "voice-avatar-worker-staging"

# AI Binding dla Cloudflare Workers AI
[ai]
binding = "AI"

# Zmienne środowiskowe (dodaj w Cloudflare Dashboard)
[vars]
ENVIRONMENT = "production"

# KV namespaces (opcjonalne - dla cache'owania)
[[kv_namespaces]]
binding = "VOICE_CACHE"
id = "voice_cache_namespace_id"
preview_id = "voice_cache_preview_id"

# Secrets (ustaw w Cloudflare Dashboard)
# wrangler secret put OPENAI_API_KEY
# wrangler secret put ELEVENLABS_API_KEY
