name = "websocket-realtime-worker"
main = "src/workers/websocket-realtime-worker.ts"
compatibility_date = "2024-01-15"
worker_dev = false
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "websocket-realtime-worker-production"

# Environment variables (set these in Cloudflare dashboard)
[vars]
# Will be set via wrangler secret put command or dashboard
# AI_GATEWAY_ACCOUNT_ID
# AI_GATEWAY_ID
# OPENAI_API_KEY
# GOOGLE_AI_STUDIO_API_KEY
# CARTESIA_API_KEY
# ELEVENLABS_API_KEY
# CLOUDFLARE_API_KEY

# Optional KV namespace for session management
# [[kv_namespaces]]
# binding = "SESSIONS"
# id = "your-kv-namespace-id"
# preview_id = "your-kv-preview-namespace-id"

# Routes (uncomment and modify as needed)
# [[env.production.routes]]
# pattern = "realtime.yourdomain.com/*"
# zone_name = "yourdomain.com"
