# POLSKIE FRONTY ZNAKÓW - Polish Music Worker Configuration
name = "polish-music-worker"
main = "polish-music-worker.js"
compatibility_date = "2024-09-15"
compatibility_flags = ["nodejs_compat"]

# Polish Team Configuration
[vars]
POLISH_TEAM_LEAD = "Jakub Kowalski"
SYSTEM_NAME = "POLSKIE_FRONTY_ZNAKOW"
LANGUAGE = "pl-PL"
TIMEZONE = "Europe/Warsaw"
FONT_SYSTEM = "Neuropol_X_Fledgling_KenyanCoffee"

# Environment dla polskich pracowników
[env.production.vars]
API_URL = "https://polish-music-worker.mybonzo.workers.dev"
TEAM_SIZE = "8"
MAIN_LIBRARIES = "3"

[env.development.vars]
API_URL = "http://localhost:8787"
DEBUG_MODE = "true"
POLISH_LOGGING = "enabled"

# Routes dla polskiego API
[[routes]]
pattern = "mybonzo.com/api/muzyka/*"
zone_name = "mybonzo.com"

[[routes]] 
pattern = "*.mybonzo.com/polish-music/*"
zone_name = "mybonzo.com"

# KV Namespaces dla polskich danych
[[kv_namespaces]]
binding = "POLISH_MUSIC_KV"
id = "polish_music_namespace"
preview_id = "polish_music_preview"

# D1 Database dla polskich utworów
[[d1_databases]]
binding = "POLISH_MUSIC_DB"
database_name = "polish-music-database"
database_id = "polish-music-db-id"

# R2 Bucket dla plików muzycznych
[[r2_buckets]]
binding = "POLISH_MUSIC_R2"
bucket_name = "polish-music-files"

# BigQuery Integration
[vars.BIGQUERY_CONFIG]
PROJECT_ID = "mybonzo-analytics"
DATASET_ID = "polish_music_data"
TABLE_ID = "track_analytics"

# Kaggle Datasets Integration
[vars.KAGGLE_CONFIG]
USERNAME = "mybonzo_team"
API_KEY = "kaggle_api_key_placeholder"
DATASETS_FOCUS = "music,polish,audio-analysis"