name = "multi-ai-assistant"
main = "src/workers/multi-ai-worker.js"
compatibility_date = "2024-08-01"

[ai]
binding = "AI"

[vars]
ENVIRONMENT = "production"

# Available models:
# @cf/qwen/qwen1.5-0.5b-chat
# @hf/thebloke/deepseek-coder-6.7b-instruct-awq  
# @cf/meta-llama/llama-2-7b-chat-hf-lora
# @cf/meta/llama-3.1-8b-instruct
