name = "ai-models-api"
main = "./src/workers/models-api.ts"
compatibility_date = "2024-01-01"

# KV namespaces for models and files
[[kv_namespaces]]
binding = "AI_MODELS"
id = "36fd4b0c086040bcabb221ee57c3169c"  # ai-models namespace

[[kv_namespaces]]
binding = "AI_FILES" 
id = "6f0b6c4984ec4f7ab159d368fcd2590d"

# AI binding for Cloudflare AI
[ai]
binding = "AI"

# Environment variables
[vars]
ENVIRONMENT = "production"
DEFAULT_LANGUAGE = "pl"
