name = "bielik-chat-assistant"
main = "src/workers/bielik-worker.js"
compatibility_date = "2024-08-01"

[env.production]
name = "bielik-chat-assistant"

[vars]
ENVIRONMENT = "production"

# HuggingFace API token will be set as a secret
# wrangler secret put HUGGINGFACE_API_TOKEN
