name = "generate-image"
main = "./src/workers/generate-image.ts"
compatibility_date = "2024-01-01"

# AI binding for Cloudflare AI
[ai]
binding = "AI"

# Environment variables
[vars]
ENVIRONMENT = "production"
