
export let agents = [
  {
    id: "POLACZEK_B",
    name: "Bibliotekarz",
    role: "Zarządzanie Wiedzą",
    goal: "Indeksowanie, wyszukiwanie i udostępnianie informacji z bazy wiedzy.",
    capabilities: ["search", "index", "retrieval", "summarize"],
    tools: ["file-reader", "vector-db", "search-api"],
    status: "idle", // active, busy, idle, error
    dependencies: ["vector-db-service"],
    performance_metrics: {
      avg_response_time: "150ms",
      queries_per_minute: 200,
      error_rate: "0.5%",
    },
  },
  {
    id: "POLACZEK_D1",
    name: "Analityk D1",
    role: "Analiza Danych",
    goal: "Wykonywanie zapytań i analiza danych w bazie D1.",
    capabilities: ["sql-query", "data-analysis", "reporting"],
    tools: ["d1-client", "query-builder"],
    status: "idle",
    dependencies: ["d1-database"],
    performance_metrics: {
      avg_response_time: "800ms",
      queries_per_minute: 50,
      error_rate: "1.2%",
    },
  },
  {
    id: "POLACZEK_DYREKTOR",
    name: "Dyrektor",
    role: "Orkiestracja Agentów",
    goal: "Zarządzanie i koordynacja pracy innych agentów POLACZEK.",
    capabilities: ["task-delegation", "workflow-management", "monitoring"],
    tools: ["agent-manager", "task-scheduler"],
    status: "active",
    dependencies: [],
    performance_metrics: {
      avg_response_time: "50ms",
      tasks_per_minute: 500,
      error_rate: "0.1%",
    },
  },
  {
    id: "POLACZEK_M1",
    name: "Manager Muzyki",
    role: "Zarządzanie Muzyką",
    goal: "Kontrolowanie odtwarzania muzyki i zarządzanie playlistami.",
    capabilities: ["play", "pause", "next", "volume-control"],
    tools: ["spotify-api", "local-player-control"],
    status: "idle",
    dependencies: ["music-player-service"],
    performance_metrics: {
      avg_response_time: "100ms",
      commands_per_minute: 100,
      error_rate: "0.2%",
    },
  },
  {
    id: "POLACZEK_T",
    name: "Tłumacz",
    role: "Tłumaczenia i Lokalizacja",
    goal: "Tłumaczenie tekstu między językami z uwzględnieniem kontekstu.",
    capabilities: ["translation", "localization", "language-detection"],
    tools: ["google-translate-api", "deepl-api"],
    status: "active",
    dependencies: [],
    performance_metrics: {
      avg_response_time: "300ms",
      translations_per_minute: 150,
      error_rate: "0.8%",
    },
  },
  {
    id: "BIELIK_AGENT",
    name: "Bielik",
    role: "Zaawansowana Analiza",
    goal: "Wykonywanie złożonych analiz i dostarczanie szczegółowych raportów.",
    capabilities: ["data-analysis", "trend-prediction", "reporting"],
    tools: ["pandas", "scikit-learn", "matplotlib"],
    status: "idle",
    dependencies: ["data-warehouse"],
    performance_metrics: {
      avg_response_time: "2500ms",
      analyses_per_hour: 20,
      error_rate: "2.5%",
    },
  },
];
